// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fornax.Core")>]
[<assembly: AssemblyProductAttribute("Fornax")>]
[<assembly: AssemblyDescriptionAttribute("Fornax is a static site generator using type safe F# DSL to define page layouts")>]
[<assembly: AssemblyVersionAttribute("0.2.0")>]
[<assembly: AssemblyFileVersionAttribute("0.2.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fornax.Core"
    let [<Literal>] AssemblyProduct = "Fornax"
    let [<Literal>] AssemblyDescription = "Fornax is a static site generator using type safe F# DSL to define page layouts"
    let [<Literal>] AssemblyVersion = "0.2.0"
    let [<Literal>] AssemblyFileVersion = "0.2.0"
