// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fornax")>]
[<assembly: AssemblyProductAttribute("Fornax")>]
[<assembly: AssemblyDescriptionAttribute("Fornax is a static site generator using type safe F# DSL to define page templates")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fornax"
    let [<Literal>] AssemblyProduct = "Fornax"
    let [<Literal>] AssemblyDescription = "Fornax is a static site generator using type safe F# DSL to define page templates"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
