name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    strategy:
      matrix:
        dotnet: [8.0.100]

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@4.3
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore tools
      run: dotnet tool restore
    - name: NuGet restore
      run: dotnet restore Fornax.sln
    - name: build and push packages
      run: dotnet run Push
      env:
        nuget-key: ${{ secrets.NUGET_KEY }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: out
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: out/*.nupkg
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true